-- 退款/退货/换货表
create table refund (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null,
    order_id    varchar(20) not null,
    type        smallint default 0,    -- 0:仅退款, 1:退货退款, 2:换货
    reason      varchar(500),
    amount      numeric(10, 2),
    status      smallint default 0,    -- 0:待审核, 1:审核通过, 2:退款中, 3:已退款, 4:已拒绝, 5:已取消
    remark      varchar(500),
    is_deleted  smallint default 0,
    create_time timestamp,
    update_time timestamp
);
alter table refund owner to postgres;
create index refund_user_id_idx on refund (user_id);
create index refund_order_id_idx on refund (order_id);
