-- 用户投诉表
create table complaint (
    id           bigint generated by default as identity primary key,
    user_id      bigint not null,
    order_id     varchar(20) not null,
    type         varchar(20) default 'service',  -- service:服务, delivery:物流, product:商品
    detail       varchar(1000),
    status       smallint default 0,              -- 0:待处理, 1:处理中, 2:已处理
    handler_note varchar(500),
    is_deleted   smallint default 0,
    create_time  timestamp,
    update_time  timestamp
);
alter table complaint owner to postgres;
create index complaint_user_id_idx on complaint (user_id);
create index complaint_order_id_idx on complaint (order_id);
