server:
  port: 8082
  servlet:
    context-path: /api
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.100:8848
        group: com.social
      config:
        server-addr: 192.168.211.100:8848
        file-extension: yaml
        group: com.social
  config:
    import:
      - optional:nacos:order-service?group=com.social&refresh=true
      - optional:nacos:social-common?group=com.social&refresh=true
